weekly-schedule:
  lectures: "#0494dc"
  live-sessions: "#EE7C2F"
  discussion: "#8f56e3"
  labs: "#F3B200"
  projects: "#62C213"
  readings: "#Cf4AD9"
  dans-oh: "#00A178"
  surveys: "#BBBBBB"
  exams: "#BB0000"